name: flutter_native_image
description: A flutter plugin which uses native iOS/Android to resize, compress or crop
version: 0.0.6+1
homepage: https://konseben.dev
issue_tracker: https://github.com/btastic/flutter_native_image/issues

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

environment:
  sdk: '>=3.0.0 <4.0.0'

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutternativeimage
        pluginClass: FlutterNativeImagePlugin
      ios:
        package: com.example.flutternativeimage
        pluginClass: FlutterNativeImagePlugin
